services:
  # A Docker web service
  - type: web
    name: indexify 
    autoDeploy: false
    env: image
    image:
      url: diptanu/indexify:latest
    #healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: 8000
      - key: ZEP_MEMORY_STORE_POSTGRES_DSN
        fromDatabase:
          name: zep-postgres
          property: connectionString
      - key: ZEP_NLP_SERVER_HOSTPORT
        fromService:
          name: zep-nlp
          type: pserv
          property: hostport
      - key: ZEP_OPENAI_API_KEY
        sync: false
  - type: pserv
    name: qdrant
    autoDeploy: false
    env: image
    image:
      url: qdrant/qdrant:v1.2.2

databases:
  - name: zep-postgres
    databaseName: zep
    postgresMajorVersion: 15
    ipAllowList: [] # only allow internal connections